bot_prefix: "command_prefix "
token: "bot_token"
application_id: "bot_application_id"
google_api_key: "your_google_api_key"
owners:
  - yourdiscordid
blacklist:
  - abuserid
main_color: 0xD75BF4
error: 0xE02B2B
success: 0x42F56C
warning: 0xF59E42
info: 0x4299F5
